config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  get '/favorites' => 'resources#favorites', as: :favorites

  resources :resources do
    member do
      put 'upvote', to: 'resources#upvote'
      put 'downvote', to: 'resources#downvote'
    end
  end

  resources :categories

  get 'pages/home'
  get 'pages/about'

  root 'pages#home'

end

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
  <% if @resource.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

      <ul>
      <% @resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, type: "text", :class => "form-control", placeholder: "Resource name" %>
  </div>
  <div class="field form-group">
    <%= f.label :link %><br>
    <%= f.text_area :link, type: "url", :class => "form-control", placeholder: "www.example.com"%>
  </div>
  <div class="field form-group">
    <%= f.label :notes %><br>
    <%= f.text_area :notes, type: "text", :class => "form-control", placeholder: "Useful notes about the resource" %>
  </div>
  <div class="field form-group">
    <%= f.label :category_id %><br>
    <% if params[:cat_id] %>
      <%= f.collection_select :category_id, @categories.order(:name), :id, :name, {prompt: 'Select a category', :selected => params[:cat_id], class: 'form-control'} %>
    <% else %>
      <%= f.collection_select :category_id, @categories.order(:name), :id, :name, {prompt: 'Select a category'}, {class: 'form-control'} %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn", type: "submit", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/resources/_resource.html.erb
<div class="col-sm-6 col-md-4">
  <div class="panel panel-default resource-panel">
    <div class="panel-body">
      <div class="row resource">
        <div class="col-xs-2 text-center">

          <div class="vote-box">
            <%= link_to fa_icon('chevron-up lg'), upvote_resource_path(resource), method: :put %><br>
            <%= resource.netvotes %><br>
            <%= link_to fa_icon('chevron-down lg'), downvote_resource_path(resource), method: :put %>
          </div>
        </div>

        <div class="col-xs-10">
          <div class="resource-icons">
            <%= link_to fa_icon('pencil'), edit_resource_path(resource), class: "btn btn-default btn-xs" %>
            <%= link_to fa_icon('trash-o'), resource, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-xs' %>
          </div> <!-- resource-icons -->

          <%= link_to resource.link, target: "_blank", :class => "resource-link" do %>
            <h4><%= resource.title %> <%= fa_icon "external-link", class: "fa-sm" %></h4>
          <% end %>
        </div>
      </div>
      <p><%= resource.notes %></p>
    </div>
  </div>
</div>

app/views/resources/edit.html.erb
<h1>Editing Resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/favorites.html.erb
<h1>Your favorite resources</h1>

<% if @resources.empty? %>
  <p>You have no favorites yet.  Go out and vote on some resources!</p>
<% else %>
  <div class="row">
    <%= render @resources %>
  </div>
<% end %>

app/views/resources/index.html.erb
<h1>Great Web Dev Resources</h1>

<div class="row">
  <div class="col-sm-3 col-md-3">
    <div class="well">
      <h4>Search</h4>
      <%= form_tag("/resources", method: "get", role: "search", class: "form") do %>
        <div class="form-group">
          <%= text_field_tag("search", nil, placeholder: "Search Resources", class: "form-control") %>
        </div>
        <%= button_tag( fa_icon('search', text: "Search"), class: "btn btn-primary") %>
      <% end %>
      <br>
      <h4>Filter</h4>
      <p>
        <%= link_to "Show All", resources_path, class: "btn btn-default btn-xs filter" %>
        <% @categories.order(:name).each do |category| %>
          <a href="?category_ids=<%= category.id%>"><button class="btn btn-default btn-xs filter <%= 'active' if params[:category_ids].to_i == category.id %>"><%= category.name %></button></a>
        <% end %>
      </p>
      <p>
        <%= link_to fa_icon('plus', text: 'Add Resource'), new_resource_path, :class => "btn btn-primary", type: "button" %>
      </p>
    </div>
  </div>

  <div class="col-sm-9 col-md-9">
    <% @resources.group_by(&:category).each do |category, resources| %>
      <h3 class="brand-text"><%= category.name %></h3>
      <div class="row">
        <%= render resources.sort_by(&:netvotes).reverse %>
      </div>
    <% end %>
  </div>
</div>

app/views/resources/new.html.erb
<h1>New Resource</h1>

<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<h3><%= @resource.title %></h3>
<p>
  <strong>Category:</strong>
  <%= @resource.category.name %>
</p>
<p>
  <%= @resource.notes %>
</p>
<p>
  <%= link_to @resource.link, @resource.link, target: "_blank" %>
</p>

<%= link_to fa_icon('pencil', text: 'Edit'), edit_resource_path(@resource), class: "btn btn-default" %>
<%= link_to fa_icon('list', text: 'All Resources'), resources_path, class: "btn btn-default" %>