config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  get '/favorites' => 'resources#favorites', as: :favorites

  resources :resources do
    member do
      put 'upvote', to: 'resources#upvote'
      put 'downvote', to: 'resources#downvote'
    end
  end

  resources :categories

  get 'pages/home'
  get 'pages/about'

  root 'pages#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :resources

  validates :name, presence: true, length: {in: 2..25}, uniqueness: true
  validates :description, presence: true, length: {in: 2..200}
end

# == Schema Information
#
# Table name: categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :update, :create, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all.order('name')
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, type: "text", :class => "form-control", placeholder: "Category name" %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, type: "text", :class => "form-control", placeholder: "Category description" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn", type: "submit", :class => "btn btn-default" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Categories</h1>
<blockquote><em>Click on a category to see links and resources for that category!</em></blockquote>

<p><%= link_to 'New Category', new_category_path, :class => "btn btn-default" %></p>

<div class="row">
  <% @categories.each do |category| %>
    <div class="col-lg-3 col-md-4 col-sm-6">
      <div class="well">
        <p>
          <a href="<%= resources_path %>?category_ids=<%= category.id%>"><button class="btn btn-warning">
            <%= category.name %></button>
          </a>
        </p>
        <p><%= truncate(category.description, length: 70) %> <%= link_to "More", category_path(category), class: "readmore" %></p>
        <div class="well-footer">
          <%= link_to fa_icon('pencil', text: 'Edit'), edit_category_path(category), class: "btn btn-default btn-xs" %>
          <%= link_to fa_icon('trash-o', text: 'Delete'), category, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-xs' %>
        </div>
      </div>
    </div>
  <% end %>

</div>

<br>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h2><%= @category.name %></h2>

<p>
  <%= @category.description %>
</p>

<ul>
  <% @category.resources.each do |resource| %>
    <li><%= link_to resource.title, resource.link, target: "_blank" %></li>
  <% end %>
</ul>

<%= link_to 'Create a New Resource for this Category', new_resource_path(cat_id: @category.id), class: 'btn btn-success' %>
<%= link_to 'Edit', edit_category_path(@category), class: 'btn btn-primary' %>
<%= link_to 'Back', categories_path, class: 'btn btn-default' %>