config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  get '/favorites' => 'resources#favorites', as: :favorites

  resources :resources do
    member do
      put 'upvote', to: 'resources#upvote'
      put 'downvote', to: 'resources#downvote'
    end
  end

  resources :categories

  get 'pages/home'
  get 'pages/about'

  root 'pages#home'

end

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'TTS Resources', root_url, :class => "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Categories", categories_url %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Resources <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Resources", resources_url %></li>
            <% if user_signed_in? %>
              <li><%= link_to "My Favorites", favorites_url %></li>
            <% end %>
          </ul>
        </li>
        <li></li>
        <li><%= link_to 'About', pages_about_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <%= render 'devise/menu/registration_items' %>
        <%= render 'devise/menu/login_items' %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>TTS Resources</title>

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.0.2/css/font-awesome.min.css">
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://code.jquery.com/jquery-1.11.2.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
  <%= javascript_include_tag "application" %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

</head>
<body>
  <header>
      <%= render 'layouts/navigation' %>
    </header>

  <div class="container-fluid">

    <% if notice.present? %>
      <div class="alert alert-dismissable alert-success">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= notice %>
      </div>
    <% end %>

    <%= yield %>
  </div>

 <footer>
    <div class="container-fluid footer">
      <div class="col-sm-4 left">
        TTS Resources &copy; <%= Time.now.year %>
      </div>

      <div class="col-sm-4 center">
        <%= link_to "Contributors", pages_about_path %>
      </div>

      <div class="col-sm-4 right">
        <a href="https://github.com/siakaramalegos/tts_resources" target="_blank"><%= fa_icon 'github', class: "fa-2x" %></a>
      </div>
    </div>
  </footer>

</body>
</html>